### ISSUE TITLE
Moving actions

### ISSUE THREAD

**Issue by smmss79** [SharifAIChallenge/AIC21-Client-Python#23]
Hi

I'm new to Python and AI and as more I search documentation for "how to send moving action to each ant or scorpion", I get less understood.
Please help, if is'nt against rules of game.
Tnx a lot
Happy new year

**Comment by MohsenDehghankar** [comment]
Hi,
If you need to send a move action, use sth like `self.direction = Direction.UP.value` in `turn` function inside AI class.
If you also need to send a message to chat box use:
`self.message = "some message"`
`self.value = 10`
