### ISSUE TITLE
No memory for Ants !!!

### ISSUE THREAD

**Issue by 733amir** [SharifAIChallenge/AIC21-Client-Python#31]
I think there is a very important problem in the clients' implementation. I understand that there should be no direct communication between each pair of ants and they should send information through the chatbox, but they should be able to save information for themselves. If ants do not have memory, they will simply run into loops as ALL algorithms have some kind of priority in decision making and can't maintain a strategy.

**Comment by MohsenDehghankar** [comment]
Hi,
You can use static fields in AI

**Comment by seriiix** [comment]
Ants _can_ save information for themselves. Although the `AI` object is regenerated every turn, you can create a memory class and save the information you need.

**Comment by 733amir** [comment]
Thanks for the help.
